name: Grizzly Alert Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'diff'
        type: choice
        options:
          - diff
          - apply
      environment:
        description: 'Environment'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - prod
      team:
        description: 'Team name'
        required: true
        default: 'devops'
        type: choice
        options:
          - devops
      service:
        description: 'Service/Resource name'
        required: true
        default: 'web-server'
        type: choice
        options:
          - web-server

env:
  GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
  GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}

permissions:
  contents: read

jobs:
  grizzly-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Grizzly
        run: |
          curl -fsSL https://github.com/grafana/grizzly/releases/latest/download/grr-linux-amd64 -o grr
          chmod +x grr
          sudo mv grr /usr/local/bin/

      - name: Install jsonnet
        run: |
          sudo apt-get update
          sudo apt-get install -y jsonnet

      - name: Set workflow variables
        run: |
          echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TEAM=${{ github.event.inputs.team }}" >> $GITHUB_ENV
          echo "SERVICE=${{ github.event.inputs.service }}" >> $GITHUB_ENV

      - name: Generate Grizzly resources
        run: |
          echo "Generating resources for:"
          echo "  Environment: $ENVIRONMENT"
          echo "  Team: $TEAM"
          echo "  Service: $SERVICE"
          echo "  Action: $ACTION"

          make generate ENVIRONMENT="$ENVIRONMENT" TEAM="$TEAM" SERVICE="$SERVICE"

      - name: Show generated resources
        run: |
          echo "=== GENERATED RESOURCES ==="
          cat resources.json

      - name: Preview changes (diff)
        if: env.ACTION == 'diff' && github.ref != "refs/heads/main"
        run: |
          echo "=== GRIZZLY DIFF ==="
          make diff ENVIRONMENT="$ENVIRONMENT" TEAM="$TEAM" SERVICE="$SERVICE"

      - name: Apply changes
        if: env.ACTION == 'apply' && github.ref == "refs/heads/main"
        run: |
          echo "=== GRIZZLY APPLY ==="
          make apply ENVIRONMENT="$ENVIRONMENT" TEAM="$TEAM" SERVICE="$SERVICE"
          echo "=== CHANGES APPLIED ==="